// Live product catalogue and prices extracted from Cloudflare D1 sf-db.
// 37 categories and 255 products with active live MRP & selling rates.
// Contains zero secrets, zero customer data, and zero image payloads.

export type SeedCategory = {
  id: string;
  line: "standard" | "elite";
  name: string;
  sort: number;
};

export type SeedProduct = {
  id: string;
  categoryId: string;
  line: "standard" | "elite";
  name: string;
  content: string;
  mrp: number;
  price: number;
  active: number;
  stock: number;
  sort: number;
};

export const SEED_CATEGORIES: SeedCategory[] = [
  { id: "elite-combo-packs-52b1", line: "elite", name: "Combo Packs", sort: 0 },
  { id: "standard-combo-packs-bd80", line: "standard", name: "Combo Packs", sort: 0 },
  { id: "elite-sparklers", line: "elite", name: "SPARKLERS", sort: 1 },
  { id: "standard-sparklers", line: "standard", name: "SPARKLERS", sort: 1 },
  { id: "elite-flower-pot", line: "elite", name: "FLOWER POTS", sort: 2 },
  { id: "standard-flower-pots", line: "standard", name: "FLOWER POTS", sort: 2 },
  { id: "elite-ground-chakkar", line: "elite", name: "GROUND CHAKKARS", sort: 3 },
  { id: "standard-fancy-fountains-5-piece", line: "standard", name: "SPECIAL FANCY FOUNTAINS", sort: 3 },
  { id: "elite-twinking-star", line: "elite", name: "TWINKLING STARS", sort: 4 },
  { id: "standard-chakkars", line: "standard", name: "GROUND CHAKKARS", sort: 4 },
  { id: "elite-one-sound-crackers", line: "elite", name: "ONE SOUND FIREWORKS", sort: 5 },
  { id: "standard-special-chakkars-0529", line: "standard", name: "SPECIAL CHAKKARS", sort: 5 },
  { id: "elite-magic-crackers-247b", line: "elite", name: "MAGIC CRACKERS", sort: 6 },
  { id: "standard-novel-fireworks-20-piece", line: "standard", name: "NOVEL FIREWORKS", sort: 6 },
  { id: "elite-paper-bomb", line: "elite", name: "PAPER BOMBS", sort: 7 },
  { id: "standard-one-sound-crackers", line: "standard", name: "ONE SOUND FIREWORKS", sort: 7 },
  { id: "elite-bomb", line: "elite", name: "BOMBS", sort: 8 },
  { id: "standard-redfort-magic-crackers-5b9e", line: "standard", name: "REDFORT MAGIC CRACKERS", sort: 8 },
  { id: "elite-rocket", line: "elite", name: "ROCKETS", sort: 9 },
  { id: "standard-attom-bomb", line: "standard", name: "BOMBS", sort: 9 },
  { id: "elite-kids-fancy-attraction-3c17", line: "elite", name: "KIDS FANCY ATTRACTION", sort: 10 },
  { id: "standard-rockets", line: "standard", name: "ROCKETS", sort: 10 },
  { id: "elite-sky-lantern-cbfd", line: "elite", name: "SKY LANTERN", sort: 11 },
  { id: "standard-fancy-fireworks", line: "standard", name: "FANCY FIREWORKS", sort: 11 },
  { id: "elite-night-fancy", line: "elite", name: "NIGHT FANCY ATTRACTION", sort: 12 },
  { id: "standard-comets", line: "standard", name: "COMETS", sort: 12 },
  { id: "elite-peacock-025e", line: "elite", name: "PEACOCK", sort: 13 },
  { id: "standard-multishots", line: "standard", name: "MULTICOLOUR SHOTS", sort: 13 },
  { id: "elite-tin-beer-fountain-cecc", line: "elite", name: "TIN BEER FOUNTAIN", sort: 14 },
  { id: "standard-0-75-cakes", line: "standard", name: "\"0.75\" MEGA SHOTS", sort: 14 },
  { id: "elite-colour-smoke-5000-wala-a6ae", line: "elite", name: "COLOUR SMOKE  5000 WALA", sort: 15 },
  { id: "standard-confetti-colour-smoke", line: "standard", name: "COLOUR SMOKE / CONFETTI", sort: 15 },
  { id: "elite-comets", line: "elite", name: "COMETS", sort: 16 },
  { id: "standard-gift-box", line: "standard", name: "GIFT BOXES", sort: 16 },
  { id: "elite-multi-shots", line: "elite", name: "MULTICOLOUR SHOTS", sort: 17 },
  { id: "elite-matches", line: "elite", name: "MATCHES", sort: 18 },
  { id: "elite-gift-box", line: "elite", name: "GIFT BOXES", sort: 19 },
];

export const SEED_PRODUCTS: SeedProduct[] = [
  { id: "elite-comets-3", categoryId: "elite-comets", line: "elite", name: "Chotta Fancy (4 variants)", content: "1 Pcs", mrp: 295, price: 59, active: 1, stock: -1, sort: 0 },
  { id: "elite-ground-chakkar-90732f", categoryId: "elite-ground-chakkar", line: "elite", name: "Ground Chakkar Big", content: "10 Pcs", mrp: 275, price: 55, active: 1, stock: -1, sort: 0 },
  { id: "elite-kids-fancy-attraction-3c17-fe8de0", categoryId: "elite-kids-fancy-attraction-3c17", line: "elite", name: "Snake Serphant Eggs", content: "50 Pcs", mrp: 250, price: 50, active: 1, stock: -1, sort: 0 },
  { id: "elite-magic-crackers-247b-9e6cc1", categoryId: "elite-magic-crackers-247b", line: "elite", name: "28 MAGIC CHORSA", content: "1 Pcs", mrp: 90, price: 18, active: 1, stock: -1, sort: 0 },
  { id: "elite-night-fancy-13", categoryId: "elite-night-fancy", line: "elite", name: "Kit Kat", content: "10 Pcs", mrp: 225, price: 45, active: 1, stock: -1, sort: 0 },
  { id: "standard-0-75-cakes-1", categoryId: "standard-0-75-cakes", line: "standard", name: "Blue Thunder (56 Shots)", content: "1 Pcs", mrp: 8662, price: 1732, active: 1, stock: -1, sort: 0 },
  { id: "standard-attom-bomb-2", categoryId: "standard-attom-bomb", line: "standard", name: "Hydrogen Bomb", content: "10 Pcs", mrp: 604, price: 121, active: 1, stock: -1, sort: 0 },
  { id: "standard-chakkars-5", categoryId: "standard-chakkars", line: "standard", name: "Red &white Chakkars", content: "10 Pcs", mrp: 410, price: 82, active: 1, stock: -1, sort: 0 },
  { id: "standard-comets-c050e3", categoryId: "standard-comets", line: "standard", name: "1\"  Super Star Double Ball (BLUE)", content: "1 Pcs", mrp: 483, price: 97, active: 1, stock: -1, sort: 0 },
  { id: "standard-fancy-fireworks-4", categoryId: "standard-fancy-fireworks", line: "standard", name: "Chat Chat", content: "10 Pcs", mrp: 446, price: 89, active: 1, stock: -1, sort: 0 },
  { id: "standard-fancy-fountains-5-piece-1", categoryId: "standard-fancy-fountains-5-piece", line: "standard", name: "Mini Fountain Red", content: "5 Pcs", mrp: 410, price: 82, active: 1, stock: -1, sort: 0 },
  { id: "standard-flower-pots-1", categoryId: "standard-flower-pots", line: "standard", name: "Flower Pot Big", content: "10 Pcs", mrp: 856, price: 171, active: 1, stock: -1, sort: 0 },
  { id: "standard-multishots-cde2e1", categoryId: "standard-multishots", line: "standard", name: "12 Shot (BALEEN)", content: "1 Pcs", mrp: 1197, price: 239, active: 1, stock: -1, sort: 0 },
  { id: "standard-one-sound-crackers-3", categoryId: "standard-one-sound-crackers", line: "standard", name: "6.5cm Sparrow", content: "5 Pcs", mrp: 94, price: 19, active: 1, stock: -1, sort: 0 },
  { id: "standard-redfort-magic-crackers-5b9e-f0f658", categoryId: "standard-redfort-magic-crackers-5b9e", line: "standard", name: "Magic Crackers -100", content: "1 Pcs", mrp: 551, price: 110, active: 1, stock: -1, sort: 0 },
  { id: "standard-rockets-1", categoryId: "standard-rockets", line: "standard", name: "Rainbow Rocket", content: "5 Pcs", mrp: 861, price: 172, active: 1, stock: -1, sort: 0 },
  { id: "standard-sparklers-1", categoryId: "standard-sparklers", line: "standard", name: "Jimmy Gold 12cm", content: "10 Pcs", mrp: 284, price: 57, active: 1, stock: -1, sort: 0 },
  { id: "elite-comets-1", categoryId: "elite-comets", line: "elite", name: "7 Shots", content: "5 Pcs", mrp: 625, price: 125, active: 1, stock: -1, sort: 1 },
  { id: "elite-ground-chakkar-1", categoryId: "elite-ground-chakkar", line: "elite", name: "Gc Special", content: "10 Pcs", mrp: 450, price: 90, active: 1, stock: -1, sort: 1 },
  { id: "elite-kids-fancy-attraction-3c17-20a6ae", categoryId: "elite-kids-fancy-attraction-3c17", line: "elite", name: "Photo Flash", content: "5 Pcs", mrp: 295, price: 59, active: 1, stock: -1, sort: 1 },
  { id: "elite-magic-crackers-247b-b879c2", categoryId: "elite-magic-crackers-247b", line: "elite", name: "28 Magic Giant", content: "1 Pcs", mrp: 130, price: 26, active: 1, stock: -1, sort: 1 },
  { id: "elite-night-fancy-22", categoryId: "elite-night-fancy", line: "elite", name: "Assorted Cartoon", content: "10 Pcs", mrp: 375, price: 75, active: 1, stock: -1, sort: 1 },
  { id: "standard-0-75-cakes-2", categoryId: "standard-0-75-cakes", line: "standard", name: "Sun Flower (100 Shots)", content: "1 Pcs", mrp: 15488, price: 3098, active: 1, stock: -1, sort: 1 },
  { id: "standard-attom-bomb-1", categoryId: "standard-attom-bomb", line: "standard", name: "Standard Hydrogen Green", content: "10 Pcs", mrp: 656, price: 131, active: 1, stock: -1, sort: 1 },
  { id: "standard-chakkars-1", categoryId: "standard-chakkars", line: "standard", name: "Zamin Chakkars Big", content: "25 Pcs", mrp: 777, price: 155, active: 1, stock: -1, sort: 1 },
  { id: "standard-comets-670f62", categoryId: "standard-comets", line: "standard", name: "1\"  Super Star Double Ball (CRACKLING)", content: "1 Pcs", mrp: 483, price: 97, active: 1, stock: -1, sort: 1 },
  { id: "standard-fancy-fireworks-11", categoryId: "standard-fancy-fireworks", line: "standard", name: "Disco Flash", content: "6 Pcs", mrp: 551, price: 110, active: 1, stock: -1, sort: 1 },
  { id: "standard-fancy-fountains-5-piece-294e0e", categoryId: "standard-fancy-fountains-5-piece", line: "standard", name: "Great Splender", content: "1 Pcs", mrp: 462, price: 92, active: 1, stock: -1, sort: 1 },
  { id: "standard-flower-pots-2", categoryId: "standard-flower-pots", line: "standard", name: "Flower Pot Special", content: "10 Pcs", mrp: 1139, price: 228, active: 1, stock: -1, sort: 1 },
  { id: "standard-multishots-3e1bd9", categoryId: "standard-multishots", line: "standard", name: "12 Shot (SKYWASH)", content: "1 Pcs", mrp: 1197, price: 239, active: 1, stock: -1, sort: 1 },
  { id: "standard-one-sound-crackers-4", categoryId: "standard-one-sound-crackers", line: "standard", name: "9cm Lakshmi", content: "5 Pcs", mrp: 163, price: 33, active: 1, stock: -1, sort: 1 },
  { id: "standard-redfort-magic-crackers-5b9e-b1b697", categoryId: "standard-redfort-magic-crackers-5b9e", line: "standard", name: "Magic Crackers -1000", content: "1 Pcs", mrp: 3124, price: 625, active: 1, stock: -1, sort: 1 },
  { id: "standard-rockets-3", categoryId: "standard-rockets", line: "standard", name: "Bomb Rocket", content: "5 Pcs", mrp: 956, price: 191, active: 1, stock: -1, sort: 1 },
  { id: "standard-sparklers-2", categoryId: "standard-sparklers", line: "standard", name: "Jimmy Clarckling 12cm", content: "10 Pcs", mrp: 299, price: 60, active: 1, stock: -1, sort: 1 },
  { id: "elite-comets-a3777d", categoryId: "elite-comets", line: "elite", name: "Gold & Silver Sky Shots", content: "10 Pcs", mrp: 925, price: 185, active: 1, stock: -1, sort: 2 },
  { id: "elite-ground-chakkar-3", categoryId: "elite-ground-chakkar", line: "elite", name: "Disco Wheel", content: "5 Pcs", mrp: 450, price: 90, active: 1, stock: -1, sort: 2 },
  { id: "elite-kids-fancy-attraction-3c17-c2a7dc", categoryId: "elite-kids-fancy-attraction-3c17", line: "elite", name: "Butterfly", content: "10 Pcs", mrp: 380, price: 76, active: 1, stock: -1, sort: 2 },
  { id: "elite-magic-crackers-247b-6a5d6a", categoryId: "elite-magic-crackers-247b", line: "elite", name: "56 MAGIC GIANT", content: "1 Pcs", mrp: 260, price: 52, active: 1, stock: -1, sort: 2 },
  { id: "elite-night-fancy-1", categoryId: "elite-night-fancy", line: "elite", name: "Star Light", content: "5 Pcs", mrp: 495, price: 99, active: 1, stock: -1, sort: 2 },
  { id: "standard-0-75-cakes-3", categoryId: "standard-0-75-cakes", line: "standard", name: "Red Roses (125 Shots)", content: "1 Pcs", mrp: 22312, price: 4462, active: 1, stock: -1, sort: 2 },
  { id: "standard-attom-bomb-3", categoryId: "standard-attom-bomb", line: "standard", name: "Thunder Bomb", content: "10 Pcs", mrp: 845, price: 169, active: 1, stock: -1, sort: 2 },
  { id: "standard-chakkars-4", categoryId: "standard-chakkars", line: "standard", name: "Whizz wheel", content: "5 Pcs", mrp: 866, price: 173, active: 1, stock: -1, sort: 2 },
  { id: "standard-comets-bcb4d8", categoryId: "standard-comets", line: "standard", name: "1 1/4\" Star Fire (RED)", content: "1 Pcs", mrp: 514, price: 103, active: 1, stock: -1, sort: 2 },
  { id: "standard-fancy-fireworks-5", categoryId: "standard-fancy-fireworks", line: "standard", name: "Signal Light", content: "5 Pcs", mrp: 709, price: 142, active: 1, stock: -1, sort: 2 },
  { id: "standard-fancy-fountains-5-piece-2", categoryId: "standard-fancy-fountains-5-piece", line: "standard", name: "Jet Foutain", content: "5 Pcs", mrp: 604, price: 121, active: 1, stock: -1, sort: 2 },
  { id: "standard-flower-pots-4", categoryId: "standard-flower-pots", line: "standard", name: "Flower Pot Deluxe", content: "5 Pcs", mrp: 1517, price: 303, active: 1, stock: -1, sort: 2 },
  { id: "standard-multishots-88eac8", categoryId: "standard-multishots", line: "standard", name: "12 Shot (ELEKTRO)", content: "1 Pcs", mrp: 1197, price: 239, active: 1, stock: -1, sort: 2 },
  { id: "standard-one-sound-crackers-5", categoryId: "standard-one-sound-crackers", line: "standard", name: "10cm Krishna", content: "5 Pcs", mrp: 226, price: 45, active: 1, stock: -1, sort: 2 },
  { id: "standard-redfort-magic-crackers-5b9e-48703c", categoryId: "standard-redfort-magic-crackers-5b9e", line: "standard", name: "Magic Crackers -2000", content: "1 Pcs", mrp: 6248, price: 1250, active: 1, stock: -1, sort: 2 },
  { id: "standard-rockets-2", categoryId: "standard-rockets", line: "standard", name: "Rohini Rocket", content: "5 Pcs", mrp: 1496, price: 299, active: 1, stock: -1, sort: 2 },
  { id: "standard-sparklers-3", categoryId: "standard-sparklers", line: "standard", name: "Gold Sparklers 15cm", content: "10 Pcs", mrp: 452, price: 90, active: 1, stock: -1, sort: 2 },
  { id: "elite-comets-1ffd7f", categoryId: "elite-comets", line: "elite", name: "Red Sky Shots", content: "10 Pcs", mrp: 925, price: 185, active: 1, stock: -1, sort: 3 },
  { id: "elite-ground-chakkar-4", categoryId: "elite-ground-chakkar", line: "elite", name: "Gc Special Spinner", content: "10 Pcs", mrp: 675, price: 135, active: 1, stock: -1, sort: 3 },
  { id: "elite-kids-fancy-attraction-3c17-45991a", categoryId: "elite-kids-fancy-attraction-3c17", line: "elite", name: "Helicopter", content: "5 Pcs", mrp: 450, price: 90, active: 1, stock: -1, sort: 3 },
  { id: "elite-magic-crackers-247b-e8aa6b", categoryId: "elite-magic-crackers-247b", line: "elite", name: "100 Magic Crackers", content: "1 Pcs", mrp: 300, price: 60, active: 1, stock: -1, sort: 3 },
  { id: "elite-night-fancy-2", categoryId: "elite-night-fancy", line: "elite", name: "Golden Drops", content: "5 Pcs", mrp: 575, price: 115, active: 1, stock: -1, sort: 3 },
  { id: "standard-0-75-cakes-4", categoryId: "standard-0-75-cakes", line: "standard", name: "Speed (200 Shots)", content: "1 Pcs", mrp: 29794, price: 5959, active: 1, stock: -1, sort: 3 },
  { id: "standard-attom-bomb-670b1a", categoryId: "standard-attom-bomb", line: "standard", name: "Colour Burst", content: "10 Pcs", mrp: 934, price: 187, active: 1, stock: -1, sort: 3 },
  { id: "standard-chakkars-2", categoryId: "standard-chakkars", line: "standard", name: "Zamin Chakkars Special", content: "10 Pcs", mrp: 971, price: 194, active: 1, stock: -1, sort: 3 },
  { id: "standard-comets-08c07d", categoryId: "standard-comets", line: "standard", name: "1 1/4\" Star Fire (PURPLE)", content: "1 Pcs", mrp: 514, price: 103, active: 1, stock: -1, sort: 3 },
  { id: "standard-fancy-fireworks-3", categoryId: "standard-fancy-fireworks", line: "standard", name: "Snow Walley", content: "1 Pcs", mrp: 866, price: 173, active: 1, stock: -1, sort: 3 },
  { id: "standard-fancy-fountains-5-piece-5", categoryId: "standard-fancy-fountains-5-piece", line: "standard", name: "Cheers Fountain", content: "3 Pcs", mrp: 1239, price: 248, active: 1, stock: -1, sort: 3 },
  { id: "standard-flower-pots-3", categoryId: "standard-flower-pots", line: "standard", name: "Flower Pot Gaints", content: "10 Pcs", mrp: 2399, price: 480, active: 1, stock: -1, sort: 3 },
  { id: "standard-multishots-c3df38", categoryId: "standard-multishots", line: "standard", name: "12 Shot (FLIPPER)", content: "1 Pcs", mrp: 1197, price: 239, active: 1, stock: -1, sort: 3 },
  { id: "standard-one-sound-crackers-6", categoryId: "standard-one-sound-crackers", line: "standard", name: "9cm Two Sound", content: "5 Pcs", mrp: 247, price: 49, active: 1, stock: -1, sort: 3 },
  { id: "standard-redfort-magic-crackers-5b9e-48a62f", categoryId: "standard-redfort-magic-crackers-5b9e", line: "standard", name: "Magic Crackers -5000", content: "1 Pcs", mrp: 15619, price: 3124, active: 1, stock: -1, sort: 3 },
  { id: "standard-sparklers-4", categoryId: "standard-sparklers", line: "standard", name: "Crackiling Sparklers 15cm", content: "10 Pcs", mrp: 509, price: 102, active: 1, stock: -1, sort: 3 },
  { id: "elite-comets-465713", categoryId: "elite-comets", line: "elite", name: "Green Sky Shots", content: "10 Pcs", mrp: 925, price: 185, active: 1, stock: -1, sort: 4 },
  { id: "elite-ground-chakkar-2", categoryId: "elite-ground-chakkar", line: "elite", name: "Gc Deluxe Spinner", content: "10 Pcs", mrp: 875, price: 175, active: 1, stock: -1, sort: 4 },
  { id: "elite-kids-fancy-attraction-3c17-486bc2", categoryId: "elite-kids-fancy-attraction-3c17", line: "elite", name: "Bambaram", content: "10 Pcs", mrp: 575, price: 115, active: 1, stock: -1, sort: 4 },
  { id: "elite-magic-crackers-247b-c01e18", categoryId: "elite-magic-crackers-247b", line: "elite", name: "1000  Magic Crackers", content: "1 Pcs", mrp: 1250, price: 250, active: 1, stock: -1, sort: 4 },
  { id: "elite-night-fancy-3", categoryId: "elite-night-fancy", line: "elite", name: "Peacock Feather", content: "5 Pcs", mrp: 575, price: 115, active: 1, stock: -1, sort: 4 },
  { id: "standard-0-75-cakes-5", categoryId: "standard-0-75-cakes", line: "standard", name: "Paradise (250 Shots)", content: "1 Pcs", mrp: 34519, price: 6904, active: 1, stock: -1, sort: 4 },
  { id: "standard-chakkars-3", categoryId: "standard-chakkars", line: "standard", name: "Zamin Chakkars Deluxe", content: "10 Pcs", mrp: 1255, price: 251, active: 1, stock: -1, sort: 4 },
  { id: "standard-comets-ab7aab", categoryId: "standard-comets", line: "standard", name: "1 1/4\" Star Fire (YELLOW)", content: "1 Pcs", mrp: 514, price: 103, active: 1, stock: -1, sort: 4 },
  { id: "standard-fancy-fireworks-2", categoryId: "standard-fancy-fireworks", line: "standard", name: "Happy Dreams", content: "1 Pcs", mrp: 892, price: 178, active: 1, stock: -1, sort: 4 },
  { id: "standard-fancy-fountains-5-piece-3", categoryId: "standard-fancy-fountains-5-piece", line: "standard", name: "Crackling King", content: "5 Pcs", mrp: 2704, price: 541, active: 1, stock: -1, sort: 4 },
  { id: "standard-flower-pots-5", categoryId: "standard-flower-pots", line: "standard", name: "Tri Color Fountains", content: "5 Pcs", mrp: 2457, price: 491, active: 1, stock: -1, sort: 4 },
  { id: "standard-multishots-36fa79", categoryId: "standard-multishots", line: "standard", name: "12 Shot (WABOT)", content: "1 Pcs", mrp: 1197, price: 239, active: 1, stock: -1, sort: 4 },
  { id: "standard-one-sound-crackers-1", categoryId: "standard-one-sound-crackers", line: "standard", name: "Red Bijili 100 Piece", content: "1 Bag", mrp: 378, price: 76, active: 1, stock: -1, sort: 4 },
  { id: "standard-redfort-magic-crackers-5b9e-2c01b5", categoryId: "standard-redfort-magic-crackers-5b9e", line: "standard", name: "Magic Crackers -10000", content: "1 Pcs", mrp: 29662, price: 5932, active: 1, stock: -1, sort: 4 },
  { id: "standard-sparklers-5", categoryId: "standard-sparklers", line: "standard", name: "Gold  Sparklers 30cm", content: "5 Pcs", mrp: 467, price: 93, active: 1, stock: -1, sort: 4 },
  { id: "elite-comets-4", categoryId: "elite-comets", line: "elite", name: "2 Comets", content: "3 Pcs", mrp: 1495, price: 299, active: 1, stock: -1, sort: 5 },
  { id: "elite-ground-chakkar-5", categoryId: "elite-ground-chakkar", line: "elite", name: "Wire Chakkar", content: "10 Pcs", mrp: 975, price: 195, active: 1, stock: -1, sort: 5 },
  { id: "elite-magic-crackers-247b-c23319", categoryId: "elite-magic-crackers-247b", line: "elite", name: "2000  Magic Crackers", content: "1 Pcs", mrp: 2500, price: 500, active: 1, stock: -1, sort: 5 },
  { id: "elite-night-fancy-15", categoryId: "elite-night-fancy", line: "elite", name: "Disco Shower", content: "5 Pcs", mrp: 600, price: 120, active: 1, stock: -1, sort: 5 },
  { id: "standard-comets-3", categoryId: "standard-comets", line: "standard", name: "1.25 Comets Avengers Special", content: "1 Pcs", mrp: 719, price: 144, active: 1, stock: -1, sort: 5 },
  { id: "standard-fancy-fireworks-1", categoryId: "standard-fancy-fireworks", line: "standard", name: "Cluster Blaster", content: "1 Pcs", mrp: 1024, price: 205, active: 1, stock: -1, sort: 5 },
  { id: "standard-fancy-fountains-5-piece-4", categoryId: "standard-fancy-fountains-5-piece", line: "standard", name: "Lavender Fountain", content: "5 Pcs", mrp: 2336, price: 467, active: 1, stock: -1, sort: 5 },
  { id: "standard-multishots-7e08b5", categoryId: "standard-multishots", line: "standard", name: "20 Shot (SHANKEY)", content: "1 Pcs", mrp: 3832, price: 766, active: 1, stock: -1, sort: 5 },
  { id: "standard-one-sound-crackers-2", categoryId: "standard-one-sound-crackers", line: "standard", name: "Striped Bigili 100 Piece", content: "1 Bag", mrp: 446, price: 89, active: 1, stock: -1, sort: 5 },
  { id: "standard-sparklers-6", categoryId: "standard-sparklers", line: "standard", name: "Crackling Sparklers 30cm", content: "5 Pcs", mrp: 509, price: 102, active: 1, stock: -1, sort: 5 },
  { id: "elite-comets-5", categoryId: "elite-comets", line: "elite", name: "3.5\" Comets Pyro Feast", content: "1 Pcs", mrp: 1725, price: 345, active: 1, stock: -1, sort: 6 },
  { id: "elite-magic-crackers-247b-638142", categoryId: "elite-magic-crackers-247b", line: "elite", name: "5000 Magic Crackers", content: "1 Pcs", mrp: 6250, price: 1250, active: 1, stock: -1, sort: 6 },
  { id: "elite-night-fancy-4", categoryId: "elite-night-fancy", line: "elite", name: "Colour Rain", content: "5 Pcs", mrp: 625, price: 125, active: 1, stock: -1, sort: 6 },
  { id: "standard-comets-6", categoryId: "standard-comets", line: "standard", name: "Pandav", content: "5 Pcs", mrp: 875, price: 184, active: 1, stock: -1, sort: 6 },
  { id: "standard-fancy-fireworks-7", categoryId: "standard-fancy-fireworks", line: "standard", name: "Golden Whistle Small", content: "5 Pcs", mrp: 1040, price: 208, active: 1, stock: -1, sort: 6 },
  { id: "standard-multishots-e6c4d9", categoryId: "standard-multishots", line: "standard", name: "20 Shot (KISMET)", content: "1 Pcs", mrp: 3832, price: 766, active: 1, stock: -1, sort: 6 },
  { id: "standard-sparklers-7", categoryId: "standard-sparklers", line: "standard", name: "Lemon Tree Sparklers 15cm", content: "10 Pcs", mrp: 394, price: 79, active: 1, stock: -1, sort: 6 },
  { id: "elite-comets-6", categoryId: "elite-comets", line: "elite", name: "3.5 Comets Nonstop", content: "1 Pcs", mrp: 1725, price: 345, active: 1, stock: -1, sort: 7 },
  { id: "elite-magic-crackers-247b-ba2e32", categoryId: "elite-magic-crackers-247b", line: "elite", name: "10000 Magic Crackers", content: "1 Pcs", mrp: 10000, price: 2000, active: 1, stock: -1, sort: 7 },
  { id: "elite-night-fancy-19", categoryId: "elite-night-fancy", line: "elite", name: "Siren Mini", content: "5 Pcs", mrp: 625, price: 125, active: 1, stock: -1, sort: 7 },
  { id: "standard-comets-879d51", categoryId: "standard-comets", line: "standard", name: "1  3/4\"  Jasmine Drops", content: "3 Pcs", mrp: 3045, price: 609, active: 1, stock: -1, sort: 7 },
  { id: "standard-fancy-fireworks-10", categoryId: "standard-fancy-fireworks", line: "standard", name: "Seven Shots", content: "5 Pcs", mrp: 1186, price: 237, active: 1, stock: -1, sort: 7 },
  { id: "standard-multishots-29eace", categoryId: "standard-multishots", line: "standard", name: "20 Shot (MIGHTY)", content: "1 Pcs", mrp: 3832, price: 766, active: 1, stock: -1, sort: 7 },
  { id: "standard-sparklers-8", categoryId: "standard-sparklers", line: "standard", name: "Lavender Sparklers 15cm", content: "10 Pcs", mrp: 520, price: 104, active: 1, stock: -1, sort: 7 },
  { id: "elite-comets-de8e56", categoryId: "elite-comets", line: "elite", name: "3.5 Comets Jol", content: "1 Pcs", mrp: 1725, price: 345, active: 1, stock: -1, sort: 8 },
  { id: "elite-night-fancy-6", categoryId: "elite-night-fancy", line: "elite", name: "Selfie Stick", content: "5 Pcs", mrp: 660, price: 132, active: 1, stock: -1, sort: 8 },
  { id: "standard-comets-4", categoryId: "standard-comets", line: "standard", name: "1  3/4\"  Colour Thunder Bolt", content: "3 Pcs", mrp: 3045, price: 609, active: 1, stock: -1, sort: 8 },
  { id: "standard-fancy-fireworks-6", categoryId: "standard-fancy-fireworks", line: "standard", name: "Colour Changing Butterfly", content: "5 Pcs", mrp: 1339, price: 268, active: 1, stock: -1, sort: 8 },
  { id: "standard-multishots-29c90e", categoryId: "standard-multishots", line: "standard", name: "20 Shot (PICK)", content: "1 Pcs", mrp: 3832, price: 766, active: 1, stock: -1, sort: 8 },
  { id: "elite-comets-03698b", categoryId: "elite-comets", line: "elite", name: "3.5 Comets Spring", content: "1 Pcs", mrp: 1725, price: 345, active: 1, stock: -1, sort: 9 },
  { id: "elite-night-fancy-16", categoryId: "elite-night-fancy", line: "elite", name: "Black & White", content: "5 Pcs", mrp: 725, price: 145, active: 1, stock: -1, sort: 9 },
  { id: "standard-comets-5", categoryId: "standard-comets", line: "standard", name: "2\"Inch Crackling Cyclone", content: "1 Pcs", mrp: 1234, price: 247, active: 1, stock: -1, sort: 9 },
  { id: "standard-fancy-fireworks-8", categoryId: "standard-fancy-fireworks", line: "standard", name: "Gold Rush", content: "5 Pcs", mrp: 1864, price: 373, active: 1, stock: -1, sort: 9 },
  { id: "standard-multishots-16b9fb", categoryId: "standard-multishots", line: "standard", name: "25 Shot (RMS)", content: "1 Pcs", mrp: 4168, price: 834, active: 1, stock: -1, sort: 9 },
  { id: "elite-comets-7", categoryId: "elite-comets", line: "elite", name: "4.5 Comets Relax", content: "1 Pcs", mrp: 1975, price: 395, active: 1, stock: -1, sort: 10 },
  { id: "elite-night-fancy-1f5403", categoryId: "elite-night-fancy", line: "elite", name: "Water Queen", content: "1 Pcs", mrp: 725, price: 145, active: 1, stock: -1, sort: 10 },
  { id: "standard-comets-b4a140", categoryId: "standard-comets", line: "standard", name: "2\"Inch Garden Of Eden", content: "1 Pcs", mrp: 1234, price: 247, active: 1, stock: -1, sort: 10 },
  { id: "standard-fancy-fireworks-18", categoryId: "standard-fancy-fireworks", line: "standard", name: "Sun Drops", content: "5 Pcs", mrp: 1864, price: 373, active: 1, stock: -1, sort: 10 },
  { id: "standard-multishots-74ce51", categoryId: "standard-multishots", line: "standard", name: "25 Shot (ROV)", content: "1 Pcs", mrp: 4168, price: 834, active: 1, stock: -1, sort: 10 },
  { id: "elite-comets-8", categoryId: "elite-comets", line: "elite", name: "4.5 Comets party Time", content: "1 Pcs", mrp: 1975, price: 395, active: 1, stock: -1, sort: 11 },
  { id: "elite-night-fancy-17", categoryId: "elite-night-fancy", line: "elite", name: "Wowers", content: "5 Pcs", mrp: 775, price: 155, active: 1, stock: -1, sort: 11 },
  { id: "standard-comets-9c3401", categoryId: "standard-comets", line: "standard", name: "2\"Inch Happy Spring", content: "1 Pcs", mrp: 1234, price: 247, active: 1, stock: -1, sort: 11 },
  { id: "standard-fancy-fireworks-9", categoryId: "standard-fancy-fireworks", line: "standard", name: "Aerial Out", content: "5 Pcs", mrp: 1916, price: 383, active: 1, stock: -1, sort: 11 },
  { id: "standard-multishots-da7af8", categoryId: "standard-multishots", line: "standard", name: "25 Shot (ROVER)", content: "1 Pcs", mrp: 4168, price: 834, active: 1, stock: -1, sort: 11 },
  { id: "elite-comets-60d7d8", categoryId: "elite-comets", line: "elite", name: "4.5 Comets Fuse", content: "1 Pcs", mrp: 1975, price: 395, active: 1, stock: -1, sort: 12 },
  { id: "elite-night-fancy-12", categoryId: "elite-night-fancy", line: "elite", name: "Money Bank", content: "3 Pcs", mrp: 875, price: 175, active: 1, stock: -1, sort: 12 },
  { id: "standard-comets-0ca43e", categoryId: "standard-comets", line: "standard", name: "2\"Inch Lavender Lights", content: "1 Pcs", mrp: 1234, price: 247, active: 1, stock: -1, sort: 12 },
  { id: "standard-fancy-fireworks-17", categoryId: "standard-fancy-fireworks", line: "standard", name: "Jil Junk Juk", content: "3 Pcs", mrp: 1954, price: 394, active: 1, stock: -1, sort: 12 },
  { id: "standard-multishots-ce7071", categoryId: "standard-multishots", line: "standard", name: "30 Shot (HOWZIT)", content: "1 Pcs", mrp: 4494, price: 899, active: 1, stock: -1, sort: 12 },
  { id: "elite-comets-d6dc25", categoryId: "elite-comets", line: "elite", name: "4.5 Comets Snickers", content: "1 Pcs", mrp: 1975, price: 395, active: 1, stock: -1, sort: 13 },
  { id: "standard-comets-7ef390", categoryId: "standard-comets", line: "standard", name: "2\"Inch Master Piece", content: "1 Pcs", mrp: 1234, price: 247, active: 1, stock: -1, sort: 13 },
  { id: "standard-fancy-fireworks-16", categoryId: "standard-fancy-fireworks", line: "standard", name: "Lazer Show", content: "3 Pcs", mrp: 2320, price: 464, active: 1, stock: -1, sort: 13 },
  { id: "standard-multishots-45d1e5", categoryId: "standard-multishots", line: "standard", name: "30 Shot (BITCOIN)", content: "1 Pcs", mrp: 4494, price: 899, active: 1, stock: -1, sort: 13 },
  { id: "elite-comets-93c5e3", categoryId: "elite-comets", line: "elite", name: "4.5 Comets Beast", content: "1 Pcs", mrp: 1975, price: 395, active: 1, stock: -1, sort: 14 },
  { id: "elite-night-fancy-23", categoryId: "elite-night-fancy", line: "elite", name: "Colour Smoke", content: "3 Pcs", mrp: 925, price: 185, active: 1, stock: -1, sort: 14 },
  { id: "standard-comets-121701", categoryId: "standard-comets", line: "standard", name: "2\"Inch Red Coral", content: "1 Pcs", mrp: 1234, price: 247, active: 1, stock: -1, sort: 14 },
  { id: "standard-fancy-fireworks-12", categoryId: "standard-fancy-fireworks", line: "standard", name: "Krack Jak", content: "3 Pcs", mrp: 2809, price: 562, active: 1, stock: -1, sort: 14 },
  { id: "standard-multishots-6cf1e7", categoryId: "standard-multishots", line: "standard", name: "30 Shot (DTH)", content: "1 Pcs", mrp: 4494, price: 899, active: 1, stock: -1, sort: 14 },
  { id: "standard-comets-36b97d", categoryId: "standard-comets", line: "standard", name: "2\"Inch Spring Willow", content: "1 Pcs", mrp: 1234, price: 247, active: 1, stock: -1, sort: 15 },
  { id: "standard-multishots-fb9f16", categoryId: "standard-multishots", line: "standard", name: "40 Shot (DRONE)", content: "1 Pcs", mrp: 6326, price: 1265, active: 1, stock: -1, sort: 15 },
  { id: "standard-comets-41f79f", categoryId: "standard-comets", line: "standard", name: "2\"Inch Sunflower", content: "1 Pcs", mrp: 1234, price: 247, active: 1, stock: -1, sort: 16 },
  { id: "standard-multishots-ce43e7", categoryId: "standard-multishots", line: "standard", name: "40 Shot (GHOST)", content: "1 Pcs", mrp: 6326, price: 1265, active: 1, stock: -1, sort: 16 },
  { id: "standard-comets-b8e314", categoryId: "standard-comets", line: "standard", name: "2\"Inch Vampire pipe", content: "1 Pcs", mrp: 1234, price: 247, active: 1, stock: -1, sort: 17 },
  { id: "standard-multishots-7847cb", categoryId: "standard-multishots", line: "standard", name: "40 Shot (KIBO)", content: "1 Pcs", mrp: 6326, price: 1265, active: 1, stock: -1, sort: 17 },
  { id: "standard-comets-fdb140", categoryId: "standard-comets", line: "standard", name: "2\"Inch Royal Gems", content: "1 Pcs", mrp: 1234, price: 247, active: 1, stock: -1, sort: 18 },
  { id: "standard-multishots-79cbc9", categoryId: "standard-multishots", line: "standard", name: "40 Shot (LANDER)", content: "1 Pcs", mrp: 6326, price: 1265, active: 1, stock: -1, sort: 18 },
  { id: "standard-comets-6f3b88", categoryId: "standard-comets", line: "standard", name: "3\" Inch Red Coconut", content: "1 Pcs", mrp: 2320, price: 464, active: 1, stock: -1, sort: 19 },
  { id: "standard-multishots-71721d", categoryId: "standard-multishots", line: "standard", name: "60 Shot (CLIPPER)", content: "1 Pcs", mrp: 7475, price: 1495, active: 1, stock: -1, sort: 19 },
  { id: "standard-comets-2ba2c4", categoryId: "standard-comets", line: "standard", name: "3\" Inch 1000 Gems", content: "1 Pcs", mrp: 2320, price: 464, active: 1, stock: -1, sort: 20 },
  { id: "standard-multishots-4066b3", categoryId: "standard-multishots", line: "standard", name: "60 Shot (FURBY)", content: "1 Pcs", mrp: 7849, price: 1570, active: 1, stock: -1, sort: 20 },
  { id: "standard-comets-2466f6", categoryId: "standard-comets", line: "standard", name: "3\" Inch Colour Changing", content: "1 Pcs", mrp: 2320, price: 464, active: 1, stock: -1, sort: 21 },
  { id: "standard-multishots-82feff", categoryId: "standard-multishots", line: "standard", name: "60 Shot (PACKAPOT)", content: "1 Pcs", mrp: 7840, price: 1570, active: 1, stock: -1, sort: 21 },
  { id: "standard-comets-e5de83", categoryId: "standard-comets", line: "standard", name: "3\" Inch Flashing Diamond", content: "1 Pcs", mrp: 2320, price: 464, active: 1, stock: -1, sort: 22 },
  { id: "standard-multishots-eb49fc", categoryId: "standard-multishots", line: "standard", name: "100 Shot (EAT R)", content: "1 Pcs", mrp: 11944, price: 2389, active: 1, stock: -1, sort: 22 },
  { id: "standard-comets-a6970c", categoryId: "standard-comets", line: "standard", name: "3\" Inch Glory", content: "1 Pcs", mrp: 2320, price: 464, active: 1, stock: -1, sort: 23 },
  { id: "standard-multishots-399a04", categoryId: "standard-multishots", line: "standard", name: "100 Shot (MATRIX)", content: "1 Pcs", mrp: 11944, price: 2389, active: 1, stock: -1, sort: 23 },
  { id: "standard-comets-854e45", categoryId: "standard-comets", line: "standard", name: "3\" Inch Kerala Beauty", content: "1 Pcs", mrp: 2320, price: 464, active: 1, stock: -1, sort: 24 },
  { id: "standard-multishots-a6b1a7", categoryId: "standard-multishots", line: "standard", name: "100 Shot (SPEED)", content: "1 Pcs", mrp: 11944, price: 2389, active: 1, stock: -1, sort: 24 },
  { id: "standard-novel-fireworks-20-piece-1", categoryId: "standard-novel-fireworks-20-piece", line: "standard", name: "45cm Twinkling Star", content: "10 Pcs", mrp: 304, price: 61, active: 1, stock: -1, sort: 24 },
  { id: "standard-multishots-e25845", categoryId: "standard-multishots", line: "standard", name: "120 Shot (MEET SPOT)", content: "1 Pcs", mrp: 13030, price: 2606, active: 1, stock: -1, sort: 25 },
  { id: "standard-novel-fireworks-20-piece-2", categoryId: "standard-novel-fireworks-20-piece", line: "standard", name: "60cm Twinkling Star", content: "10 Pcs", mrp: 494, price: 99, active: 1, stock: -1, sort: 25 },
  { id: "standard-multishots-257b3c", categoryId: "standard-multishots", line: "standard", name: "120 Shot (SAFFIRE)", content: "1 Pcs", mrp: 13030, price: 2606, active: 1, stock: -1, sort: 26 },
  { id: "standard-novel-fireworks-20-piece-3", categoryId: "standard-novel-fireworks-20-piece", line: "standard", name: "Multicolour Candel", content: "10 Pcs", mrp: 635, price: 127, active: 1, stock: -1, sort: 26 },
  { id: "standard-multishots-1dc722", categoryId: "standard-multishots", line: "standard", name: "120 Shot (RIX)", content: "1 Pcs", mrp: 13030, price: 2606, active: 1, stock: -1, sort: 27 },
  { id: "standard-multishots-a4000a", categoryId: "standard-multishots", line: "standard", name: "240 Shot (RAINBOW DANCE)", content: "1 Pcs", mrp: 31238, price: 6248, active: 1, stock: -1, sort: 28 },
  { id: "standard-confetti-colour-smoke-1", categoryId: "standard-confetti-colour-smoke", line: "standard", name: "Color Fog Fountain", content: "5 Pcs", mrp: 604, price: 121, active: 1, stock: -1, sort: 80 },
  { id: "standard-confetti-colour-smoke-2", categoryId: "standard-confetti-colour-smoke", line: "standard", name: "Rainbow Smoke", content: "2 Pcs", mrp: 1297, price: 259, active: 1, stock: -1, sort: 81 },
  { id: "standard-confetti-colour-smoke-3", categoryId: "standard-confetti-colour-smoke", line: "standard", name: "Magic Spray", content: "5 Pcs", mrp: 1208, price: 242, active: 1, stock: -1, sort: 82 },
  { id: "standard-gift-box-1", categoryId: "standard-gift-box", line: "standard", name: "Gods Gift (25 Items)", content: "1 Pcs", mrp: 4174, price: 835, active: 1, stock: -1, sort: 84 },
  { id: "standard-gift-box-2", categoryId: "standard-gift-box", line: "standard", name: "Super (28 Items)", content: "1 Pcs", mrp: 4331, price: 866, active: 1, stock: -1, sort: 85 },
  { id: "standard-gift-box-3", categoryId: "standard-gift-box", line: "standard", name: "Great (31 Items)", content: "1 Pcs", mrp: 6216, price: 1243, active: 1, stock: -1, sort: 86 },
  { id: "standard-gift-box-4", categoryId: "standard-gift-box", line: "standard", name: "Fantastic (37 Items)", content: "1 Pcs", mrp: 7586, price: 1517, active: 1, stock: -1, sort: 87 },
  { id: "standard-gift-box-5", categoryId: "standard-gift-box", line: "standard", name: "Diamond (50 Items)", content: "1 Pcs", mrp: 11414, price: 2283, active: 1, stock: -1, sort: 88 },
  { id: "standard-gift-box-6", categoryId: "standard-gift-box", line: "standard", name: "Titan (55 Items)", content: "1 Pcs", mrp: 13114, price: 2623, active: 1, stock: -1, sort: 89 },
  { id: "elite-sparklers-1", categoryId: "elite-sparklers", line: "elite", name: "15cm Electric", content: "10 Pcs", mrp: 225, price: 45, active: 1, stock: -1, sort: 96 },
  { id: "elite-sparklers-2", categoryId: "elite-sparklers", line: "elite", name: "15cm Colour", content: "10 Pcs", mrp: 240, price: 48, active: 1, stock: -1, sort: 97 },
  { id: "elite-sparklers-3", categoryId: "elite-sparklers", line: "elite", name: "15cm Green", content: "10 Pcs", mrp: 265, price: 53, active: 1, stock: -1, sort: 98 },
  { id: "elite-sparklers-4", categoryId: "elite-sparklers", line: "elite", name: "15cm Red", content: "10 Pcs", mrp: 290, price: 58, active: 1, stock: -1, sort: 99 },
  { id: "elite-sparklers-5", categoryId: "elite-sparklers", line: "elite", name: "30cm Electric", content: "5 Pcs", mrp: 225, price: 45, active: 1, stock: -1, sort: 100 },
  { id: "elite-sparklers-6", categoryId: "elite-sparklers", line: "elite", name: "30cm Colour", content: "5 Pcs", mrp: 240, price: 48, active: 1, stock: -1, sort: 101 },
  { id: "elite-sparklers-7", categoryId: "elite-sparklers", line: "elite", name: "50cm Electric", content: "5 Pcs", mrp: 975, price: 195, active: 1, stock: -1, sort: 102 },
  { id: "elite-sparklers-8", categoryId: "elite-sparklers", line: "elite", name: "50cm Colour", content: "5 Pcs", mrp: 995, price: 199, active: 1, stock: -1, sort: 103 },
  { id: "elite-flower-pot-1", categoryId: "elite-flower-pot", line: "elite", name: "Flower Pot Big", content: "10 Pcs", mrp: 450, price: 90, active: 1, stock: -1, sort: 104 },
  { id: "elite-flower-pot-2", categoryId: "elite-flower-pot", line: "elite", name: "Flower Pot Special", content: "10 Pcs", mrp: 625, price: 125, active: 1, stock: -1, sort: 105 },
  { id: "elite-flower-pot-3", categoryId: "elite-flower-pot", line: "elite", name: "Flower Pot Ashoka", content: "10 Pcs", mrp: 700, price: 140, active: 1, stock: -1, sort: 106 },
  { id: "elite-flower-pot-4", categoryId: "elite-flower-pot", line: "elite", name: "Colour Koti", content: "10 Pcs", mrp: 1175, price: 235, active: 1, stock: -1, sort: 107 },
  { id: "elite-flower-pot-5", categoryId: "elite-flower-pot", line: "elite", name: "Tri Colour", content: "5 Pcs", mrp: 1275, price: 255, active: 1, stock: -1, sort: 108 },
  { id: "elite-twinking-star-1", categoryId: "elite-twinking-star", line: "elite", name: "1.5 Twinkling Star", content: "10 Pcs", mrp: 220, price: 44, active: 1, stock: -1, sort: 114 },
  { id: "elite-twinking-star-2", categoryId: "elite-twinking-star", line: "elite", name: "4 Twinkling Star", content: "10 Pcs", mrp: 375, price: 75, active: 1, stock: -1, sort: 115 },
  { id: "elite-one-sound-crackers-1", categoryId: "elite-one-sound-crackers", line: "elite", name: "2.75 Kuruvi", content: "5 Pcs", mrp: 45, price: 9, active: 1, stock: -1, sort: 116 },
  { id: "elite-one-sound-crackers-2", categoryId: "elite-one-sound-crackers", line: "elite", name: "3.5 Lakshmi", content: "5 Pcs", mrp: 90, price: 18, active: 1, stock: -1, sort: 117 },
  { id: "elite-one-sound-crackers-3", categoryId: "elite-one-sound-crackers", line: "elite", name: "4 Elephant", content: "5 Pcs", mrp: 120, price: 24, active: 1, stock: -1, sort: 118 },
  { id: "elite-one-sound-crackers-4", categoryId: "elite-one-sound-crackers", line: "elite", name: "4 Dlx Lakshmi", content: "5 Pcs", mrp: 175, price: 35, active: 1, stock: -1, sort: 119 },
  { id: "elite-one-sound-crackers-5", categoryId: "elite-one-sound-crackers", line: "elite", name: "4 Gold Lakshmi", content: "5 Pcs", mrp: 200, price: 40, active: 1, stock: -1, sort: 120 },
  { id: "elite-one-sound-crackers-6", categoryId: "elite-one-sound-crackers", line: "elite", name: "5 Himalayan", content: "5 Pcs", mrp: 275, price: 55, active: 1, stock: -1, sort: 121 },
  { id: "elite-one-sound-crackers-7", categoryId: "elite-one-sound-crackers", line: "elite", name: "2 Sound Crackers", content: "5 Pcs", mrp: 190, price: 38, active: 1, stock: -1, sort: 122 },
  { id: "elite-one-sound-crackers-8", categoryId: "elite-one-sound-crackers", line: "elite", name: "Bijili 50pcs", content: "1 Bag", mrp: 175, price: 35, active: 1, stock: -1, sort: 123 },
  { id: "elite-one-sound-crackers-9", categoryId: "elite-one-sound-crackers", line: "elite", name: "Bijili 100 Pcs", content: "1 Bag", mrp: 275, price: 55, active: 1, stock: -1, sort: 124 },
  { id: "elite-bomb-1", categoryId: "elite-bomb", line: "elite", name: "Bullet Bomb", content: "10 Pcs", mrp: 275, price: 55, active: 1, stock: -1, sort: 125 },
  { id: "elite-bomb-2", categoryId: "elite-bomb", line: "elite", name: "Classsic Bomb", content: "10 Pcs", mrp: 630, price: 126, active: 1, stock: -1, sort: 126 },
  { id: "elite-bomb-3", categoryId: "elite-bomb", line: "elite", name: "Agni Bomb", content: "10 Pcs", mrp: 1125, price: 225, active: 1, stock: -1, sort: 127 },
  { id: "elite-bomb-4", categoryId: "elite-bomb", line: "elite", name: "Digital Bomb", content: "10 Pcs", mrp: 1400, price: 280, active: 1, stock: -1, sort: 128 },
  { id: "elite-paper-bomb-1", categoryId: "elite-paper-bomb", line: "elite", name: "250gm", content: "1 Pcs", mrp: 300, price: 60, active: 1, stock: -1, sort: 129 },
  { id: "elite-paper-bomb-2", categoryId: "elite-paper-bomb", line: "elite", name: "500gm", content: "1 Pcs", mrp: 575, price: 115, active: 1, stock: -1, sort: 130 },
  { id: "elite-paper-bomb-3", categoryId: "elite-paper-bomb", line: "elite", name: "1000gm", content: "1 Pcs", mrp: 990, price: 198, active: 1, stock: -1, sort: 131 },
  { id: "elite-rocket-1", categoryId: "elite-rocket", line: "elite", name: "Baby Rocket", content: "10 Pcs", mrp: 345, price: 69, active: 1, stock: -1, sort: 132 },
  { id: "elite-rocket-2", categoryId: "elite-rocket", line: "elite", name: "Lunik Rocket", content: "10 Pcs", mrp: 675, price: 135, active: 1, stock: -1, sort: 133 },
  { id: "elite-rocket-3", categoryId: "elite-rocket", line: "elite", name: "Whistling Rocket", content: "5 Pcs", mrp: 895, price: 179, active: 1, stock: -1, sort: 134 },
  { id: "elite-multi-shots-1", categoryId: "elite-multi-shots", line: "elite", name: "12 Rider", content: "1 Pcs", mrp: 925, price: 185, active: 1, stock: -1, sort: 169 },
  { id: "elite-multi-shots-2", categoryId: "elite-multi-shots", line: "elite", name: "25 Rider", content: "1 Pcs", mrp: 1475, price: 295, active: 1, stock: -1, sort: 170 },
  { id: "elite-multi-shots-3", categoryId: "elite-multi-shots", line: "elite", name: "30 Shots", content: "1 Pcs", mrp: 2750, price: 550, active: 1, stock: -1, sort: 171 },
  { id: "elite-multi-shots-4", categoryId: "elite-multi-shots", line: "elite", name: "60 Shots", content: "1 Pcs", mrp: 5500, price: 1100, active: 1, stock: -1, sort: 172 },
  { id: "elite-multi-shots-5", categoryId: "elite-multi-shots", line: "elite", name: "120 Shots", content: "1 Pcs", mrp: 9750, price: 1950, active: 1, stock: -1, sort: 173 },
  { id: "elite-multi-shots-6", categoryId: "elite-multi-shots", line: "elite", name: "240 Shots", content: "1 Pcs", mrp: 19500, price: 3900, active: 1, stock: -1, sort: 174 },
  { id: "elite-matches-1", categoryId: "elite-matches", line: "elite", name: "Royal Super Deluxe", content: "5OP", mrp: 475, price: 95, active: 1, stock: -1, sort: 175 },
  { id: "elite-matches-2", categoryId: "elite-matches", line: "elite", name: "Lion Matches", content: "100 Pcs", mrp: 875, price: 175, active: 1, stock: -1, sort: 176 },
  { id: "elite-matches-3", categoryId: "elite-matches", line: "elite", name: "Royal Matches", content: "100 Pcs", mrp: 1495, price: 299, active: 1, stock: -1, sort: 177 },
  { id: "elite-gift-box-1", categoryId: "elite-gift-box", line: "elite", name: "20 Items", content: "1 Box", mrp: 2075, price: 415, active: 1, stock: -1, sort: 178 },
  { id: "elite-gift-box-2", categoryId: "elite-gift-box", line: "elite", name: "30 Items", content: "1 Box", mrp: 2850, price: 570, active: 1, stock: -1, sort: 179 },
  { id: "elite-gift-box-3", categoryId: "elite-gift-box", line: "elite", name: "40 Items", content: "1 Box", mrp: 3975, price: 795, active: 1, stock: -1, sort: 180 },
  { id: "elite-gift-box-4", categoryId: "elite-gift-box", line: "elite", name: "50 Items", content: "1 Box", mrp: 6000, price: 1200, active: 1, stock: -1, sort: 181 },
  { id: "elite-peacock-025e-1eacfd", categoryId: "elite-peacock-025e", line: "elite", name: "5 Eyes Bada Peacock(2in1purple)", content: "1 Pcs", mrp: 2125, price: 425, active: 1, stock: -1, sort: 9999 },
  { id: "elite-peacock-025e-60cdb0", categoryId: "elite-peacock-025e", line: "elite", name: "3 Eyes (Silver)", content: "1 Pcs", mrp: 925, price: 185, active: 1, stock: -1, sort: 9999 },
  { id: "elite-peacock-025e-bc564d", categoryId: "elite-peacock-025e", line: "elite", name: "3 Eyes (Red&Green)", content: "1 Pcs", mrp: 775, price: 155, active: 1, stock: -1, sort: 9999 },
  { id: "elite-peacock-025e-fd3a89", categoryId: "elite-peacock-025e", line: "elite", name: "3 Eyes (Gold)", content: "1 Pcs", mrp: 925, price: 185, active: 1, stock: -1, sort: 9999 },
  { id: "elite-tin-beer-fountain-cecc-78cfa7", categoryId: "elite-tin-beer-fountain-cecc", line: "elite", name: "White Thunder", content: "1 Pcs", mrp: 625, price: 125, active: 1, stock: -1, sort: 9999 },
  { id: "elite-tin-beer-fountain-cecc-8ab7db", categoryId: "elite-tin-beer-fountain-cecc", line: "elite", name: "Orange Crackling", content: "1 Pcs", mrp: 625, price: 125, active: 1, stock: -1, sort: 9999 },
  { id: "elite-tin-beer-fountain-cecc-8e47cf", categoryId: "elite-tin-beer-fountain-cecc", line: "elite", name: "Green Grapes Crackling", content: "1 Pcs", mrp: 625, price: 125, active: 1, stock: -1, sort: 9999 },
  { id: "elite-tin-beer-fountain-cecc-a254be", categoryId: "elite-tin-beer-fountain-cecc", line: "elite", name: "Water Melon Crackling", content: "1 Pcs", mrp: 625, price: 125, active: 1, stock: -1, sort: 9999 },
  { id: "elite-tin-beer-fountain-cecc-cddb2f", categoryId: "elite-tin-beer-fountain-cecc", line: "elite", name: "Straw berry", content: "1 Pcs", mrp: 625, price: 125, active: 1, stock: -1, sort: 9999 },
  { id: "elite-tin-beer-fountain-cecc-de6370", categoryId: "elite-tin-beer-fountain-cecc", line: "elite", name: "White Crackling", content: "1 Pcs", mrp: 625, price: 125, active: 1, stock: -1, sort: 9999 },
  { id: "standard-special-chakkars-0529-146199", categoryId: "standard-special-chakkars-0529", line: "standard", name: "Poker Wheel", content: "5 Pcs", mrp: 1759, price: 352, active: 1, stock: -1, sort: 9999 },
  { id: "standard-special-chakkars-0529-696d1e", categoryId: "standard-special-chakkars-0529", line: "standard", name: "Cuckoo Wheel", content: "5 Pcs", mrp: 1811, price: 362, active: 1, stock: -1, sort: 9999 },
  { id: "standard-special-chakkars-0529-bf9d7d", categoryId: "standard-special-chakkars-0529", line: "standard", name: "Swastik Wheel", content: "5 Pcs", mrp: 1847, price: 375, active: 1, stock: -1, sort: 9999 },
  { id: "standard-special-chakkars-0529-ee0281", categoryId: "standard-special-chakkars-0529", line: "standard", name: "Dollor wheel", content: "5 Pcs", mrp: 1759, price: 352, active: 1, stock: -1, sort: 9999 },
  { id: "elite-sky-lantern-cbfd-681712", categoryId: "elite-sky-lantern-cbfd", line: "elite", name: "Sky Lantern (PINK)", content: "1 Pcs", mrp: 275, price: 55, active: 1, stock: -1, sort: 10006 },
  { id: "elite-sky-lantern-cbfd-a9dc53", categoryId: "elite-sky-lantern-cbfd", line: "elite", name: "Sky Lantern (ORANGE)", content: "1 Pcs", mrp: 275, price: 55, active: 1, stock: -1, sort: 10007 },
  { id: "elite-sky-lantern-cbfd-be8204", categoryId: "elite-sky-lantern-cbfd", line: "elite", name: "Sky Lantern (BLUE)", content: "1 Pcs", mrp: 275, price: 55, active: 1, stock: -1, sort: 10008 },
  { id: "elite-sky-lantern-cbfd-423411", categoryId: "elite-sky-lantern-cbfd", line: "elite", name: "Sky Lantern (YELLOW)", content: "1 Pcs", mrp: 275, price: 55, active: 1, stock: -1, sort: 10009 },
  { id: "elite-colour-smoke-5000-wala-a6ae-b63a69", categoryId: "elite-colour-smoke-5000-wala-a6ae", line: "elite", name: "Blue Magic Sound", content: "1 Pcs", mrp: 1175, price: 235, active: 1, stock: -1, sort: 10010 },
  { id: "elite-colour-smoke-5000-wala-a6ae-935fad", categoryId: "elite-colour-smoke-5000-wala-a6ae", line: "elite", name: "Green Magic Sound", content: "1 Pcs", mrp: 1175, price: 235, active: 1, stock: -1, sort: 10011 },
  { id: "elite-colour-smoke-5000-wala-a6ae-59d526", categoryId: "elite-colour-smoke-5000-wala-a6ae", line: "elite", name: "Pink Magic Sound", content: "1 Pcs", mrp: 1175, price: 235, active: 1, stock: -1, sort: 10012 },
  { id: "elite-colour-smoke-5000-wala-a6ae-756005", categoryId: "elite-colour-smoke-5000-wala-a6ae", line: "elite", name: "Orange Magic Sound", content: "1 Pcs", mrp: 1175, price: 235, active: 1, stock: -1, sort: 10013 },
  { id: "elite-one-sound-crackers-0fcb51", categoryId: "elite-one-sound-crackers", line: "elite", name: "Striped Bigili 100 Piece", content: "1 Bag", mrp: 325, price: 65, active: 1, stock: -1, sort: 10015 },
  { id: "elite-combo-packs-52b1-e75eb0", categoryId: "elite-combo-packs-52b1", line: "elite", name: "Iron Man Combo", content: "40 Items", mrp: 0, price: 3500, active: 1, stock: -1, sort: 10016 },
  { id: "elite-combo-packs-52b1-3c9a1c", categoryId: "elite-combo-packs-52b1", line: "elite", name: "Captain America Combo", content: "56 Items", mrp: 0, price: 6000, active: 1, stock: -1, sort: 10017 },
  { id: "elite-combo-packs-52b1-eba56b", categoryId: "elite-combo-packs-52b1", line: "elite", name: "Hulk Combo", content: "68 Items", mrp: 0, price: 10000, active: 1, stock: -1, sort: 10018 },
  { id: "standard-combo-packs-bd80-844c93", categoryId: "standard-combo-packs-bd80", line: "standard", name: "Spider Man Combo", content: "35 Items", mrp: 0, price: 5000, active: 1, stock: -1, sort: 10019 },
  { id: "standard-combo-packs-bd80-34047a", categoryId: "standard-combo-packs-bd80", line: "standard", name: "Batman Combo", content: "51 Items", mrp: 0, price: 10000, active: 1, stock: -1, sort: 10020 },
  { id: "standard-combo-packs-bd80-2908f0", categoryId: "standard-combo-packs-bd80", line: "standard", name: "Superman Combo", content: "61 Items", mrp: 0, price: 15000, active: 1, stock: -1, sort: 10021 },
  { id: "standard-fancy-fountains-5-piece-c62067", categoryId: "standard-fancy-fountains-5-piece", line: "standard", name: "Jewel Pots", content: "5 Pcs", mrp: 1796, price: 359, active: 1, stock: -1, sort: 10022 },
  { id: "standard-0-75-cakes-bfd1b2", categoryId: "standard-0-75-cakes", line: "standard", name: "OH! Kolkata! (500 shots)", content: "1 Pcs", mrp: 71269, price: 14254, active: 1, stock: -1, sort: 10023 },
  { id: "elite-twinking-star-4816f5", categoryId: "elite-twinking-star", line: "elite", name: "Lazer Pencil", content: "10 Pcs", mrp: 450, price: 90, active: 1, stock: -1, sort: 10024 },
];
